// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | FeaturedProductsSlice
  | BestSellerSectionSlice
  | DiscountSectionSlice
  | ShopByCategorySliceSlice
  | BiographySlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactFormSectionSlice
  | ProductListSlice
  | TalkAboutSlice
  | BestSellerSectionSlice
  | FeaturedProductsSlice
  | MyValuesSlice
  | DiscountSectionSlice
  | ImageRightSlice
  | ImageLeftSlice
  | BiographySlice
  | ShopByCategorySliceSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Products documents
 */
interface ProductsDocumentData {
  /**
   * Product Name field in *Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.product_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_name: prismic.KeyTextField;

  /**
   * Product Image field in *Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.product_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Product Price field in *Products*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: products.product_price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  product_price: prismic.NumberField;

  /**
   * Is Featured field in *Products*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: products.is_featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_featured: prismic.BooleanField;
}

/**
 * Products document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductsDocumentData>,
    "products",
    Lang
  >;

/**
 * Item in *Settings → Header Label*
 */
export interface SettingsDocumentDataHeaderLabelItem {}

/**
 * Item in *Settings → Nav Settings*
 */
export interface SettingsDocumentDataNavSettingsItem {
  /**
   * Nav Label field in *Settings → Nav Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_settings[].nav_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nav_label: prismic.KeyTextField;

  /**
   * Nav Link field in *Settings → Nav Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_settings[].nav_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav_link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Header Label field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_label[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header_label: prismic.GroupField<
    Simplify<SettingsDocumentDataHeaderLabelItem>
  >;

  /**
   * Nav Settings field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_settings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_settings: prismic.GroupField<
    Simplify<SettingsDocumentDataNavSettingsItem>
  >;

  /**
   * CTA Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PageDocument
  | ProductsDocument
  | SettingsDocument;

/**
 * Default variation for BestSellerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BestSellerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BestSellerSection*
 */
type BestSellerSectionSliceVariation = BestSellerSectionSliceDefault;

/**
 * BestSellerSection Shared Slice
 *
 * - **API ID**: `best_seller_section`
 * - **Description**: BestSellerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BestSellerSectionSlice = prismic.SharedSlice<
  "best_seller_section",
  BestSellerSectionSliceVariation
>;

/**
 * Primary content in *Biography → Primary*
 */
export interface BiographySliceDefaultPrimary {
  /**
   * Owner Image field in *Biography → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: biography.primary.owner_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  owner_image: prismic.ImageField<never>;

  /**
   * Heading field in *Biography → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: biography.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Biography → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: biography.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Biography Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BiographySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BiographySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Biography*
 */
type BiographySliceVariation = BiographySliceDefault;

/**
 * Biography Shared Slice
 *
 * - **API ID**: `biography`
 * - **Description**: Biography
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BiographySlice = prismic.SharedSlice<
  "biography",
  BiographySliceVariation
>;

/**
 * Primary content in *ContactFormSection → Primary*
 */
export interface ContactFormSectionSliceDefaultPrimary {
  /**
   * Heading field in *ContactFormSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ContactFormSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Contact Image field in *ContactFormSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form_section.primary.contact_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  contact_image: prismic.ImageField<never>;
}

/**
 * Default variation for ContactFormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactFormSection*
 */
type ContactFormSectionSliceVariation = ContactFormSectionSliceDefault;

/**
 * ContactFormSection Shared Slice
 *
 * - **API ID**: `contact_form_section`
 * - **Description**: ContactFormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSlice = prismic.SharedSlice<
  "contact_form_section",
  ContactFormSectionSliceVariation
>;

/**
 * Primary content in *DiscountSection → Items*
 */
export interface DiscountSectionSliceDefaultItem {
  /**
   * Card Background Image field in *DiscountSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: discount_section.items[].card_background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_background_image: prismic.ImageField<never>;

  /**
   * Card Heading field in *DiscountSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discount_section.items[].card_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_heading: prismic.KeyTextField;

  /**
   * Card Tagline field in *DiscountSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: discount_section.items[].card_tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_tagline: prismic.KeyTextField;
}

/**
 * Default variation for DiscountSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscountSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<DiscountSectionSliceDefaultItem>
>;

/**
 * Slice variation for *DiscountSection*
 */
type DiscountSectionSliceVariation = DiscountSectionSliceDefault;

/**
 * DiscountSection Shared Slice
 *
 * - **API ID**: `discount_section`
 * - **Description**: DiscountSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscountSectionSlice = prismic.SharedSlice<
  "discount_section",
  DiscountSectionSliceVariation
>;

/**
 * Default variation for FeaturedProducts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *FeaturedProducts*
 */
type FeaturedProductsSliceVariation = FeaturedProductsSliceDefault;

/**
 * FeaturedProducts Shared Slice
 *
 * - **API ID**: `featured_products`
 * - **Description**: FeaturedProducts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSlice = prismic.SharedSlice<
  "featured_products",
  FeaturedProductsSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_heading: prismic.KeyTextField;

  /**
   * Hero Tagline field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_tagline: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageLeft → Primary*
 */
export interface ImageLeftSliceDefaultPrimary {
  /**
   * Section Image field in *ImageLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_left.primary.section_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_image: prismic.ImageField<never>;

  /**
   * Section Content field in *ImageLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_left.primary.section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;
}

/**
 * Default variation for ImageLeft Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageLeftSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageLeftSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageLeft*
 */
type ImageLeftSliceVariation = ImageLeftSliceDefault;

/**
 * ImageLeft Shared Slice
 *
 * - **API ID**: `image_left`
 * - **Description**: ImageLeft
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageLeftSlice = prismic.SharedSlice<
  "image_left",
  ImageLeftSliceVariation
>;

/**
 * Primary content in *ImageRight → Primary*
 */
export interface ImageRightSliceDefaultPrimary {
  /**
   * Section Image field in *ImageRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.section_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_image: prismic.ImageField<never>;

  /**
   * Section Content field in *ImageRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;
}

/**
 * Default variation for ImageRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageRightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageRightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageRight*
 */
type ImageRightSliceVariation = ImageRightSliceDefault;

/**
 * ImageRight Shared Slice
 *
 * - **API ID**: `image_right`
 * - **Description**: ImageRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageRightSlice = prismic.SharedSlice<
  "image_right",
  ImageRightSliceVariation
>;

/**
 * Primary content in *MyValues → Items*
 */
export interface MyValuesSliceDefaultItem {
  /**
   * Value Heading field in *MyValues → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: my_values.items[].value_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value_heading: prismic.KeyTextField;

  /**
   * Value Text field in *MyValues → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: my_values.items[].value_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value_text: prismic.KeyTextField;
}

/**
 * Default variation for MyValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MyValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MyValuesSliceDefaultItem>
>;

/**
 * Slice variation for *MyValues*
 */
type MyValuesSliceVariation = MyValuesSliceDefault;

/**
 * MyValues Shared Slice
 *
 * - **API ID**: `my_values`
 * - **Description**: MyValues
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MyValuesSlice = prismic.SharedSlice<
  "my_values",
  MyValuesSliceVariation
>;

/**
 * Default variation for ProductList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ProductList*
 */
type ProductListSliceVariation = ProductListSliceDefault;

/**
 * ProductList Shared Slice
 *
 * - **API ID**: `product_list`
 * - **Description**: ProductList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductListSlice = prismic.SharedSlice<
  "product_list",
  ProductListSliceVariation
>;

/**
 * Primary content in *ShopByCategorySlice → Primary*
 */
export interface ShopByCategorySliceSliceDefaultPrimary {
  /**
   * Heading field in *ShopByCategorySlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_by_category_slice.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ShopByCategorySlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_by_category_slice.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *ShopByCategorySlice → Items*
 */
export interface ShopByCategorySliceSliceDefaultItem {
  /**
   * Category Name field in *ShopByCategorySlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_by_category_slice.items[].category_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_name: prismic.KeyTextField;

  /**
   * Category Image field in *ShopByCategorySlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_by_category_slice.items[].category_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  category_image: prismic.ImageField<never>;
}

/**
 * Default variation for ShopByCategorySlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopByCategorySliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShopByCategorySliceSliceDefaultPrimary>,
  Simplify<ShopByCategorySliceSliceDefaultItem>
>;

/**
 * Slice variation for *ShopByCategorySlice*
 */
type ShopByCategorySliceSliceVariation = ShopByCategorySliceSliceDefault;

/**
 * ShopByCategorySlice Shared Slice
 *
 * - **API ID**: `shop_by_category_slice`
 * - **Description**: ShopByCategorySlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopByCategorySliceSlice = prismic.SharedSlice<
  "shop_by_category_slice",
  ShopByCategorySliceSliceVariation
>;

/**
 * Primary content in *TalkAbout → Items*
 */
export interface TalkAboutSliceDefaultItem {
  /**
   * Hobby Name field in *TalkAbout → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: talk_about.items[].hobby_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hobby_name: prismic.KeyTextField;

  /**
   * Hobby Image field in *TalkAbout → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: talk_about.items[].hobby_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hobby_image: prismic.ImageField<never>;
}

/**
 * Default variation for TalkAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TalkAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TalkAboutSliceDefaultItem>
>;

/**
 * Slice variation for *TalkAbout*
 */
type TalkAboutSliceVariation = TalkAboutSliceDefault;

/**
 * TalkAbout Shared Slice
 *
 * - **API ID**: `talk_about`
 * - **Description**: TalkAbout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TalkAboutSlice = prismic.SharedSlice<
  "talk_about",
  TalkAboutSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductsDocument,
      ProductsDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataHeaderLabelItem,
      SettingsDocumentDataNavSettingsItem,
      AllDocumentTypes,
      BestSellerSectionSlice,
      BestSellerSectionSliceVariation,
      BestSellerSectionSliceDefault,
      BiographySlice,
      BiographySliceDefaultPrimary,
      BiographySliceVariation,
      BiographySliceDefault,
      ContactFormSectionSlice,
      ContactFormSectionSliceDefaultPrimary,
      ContactFormSectionSliceVariation,
      ContactFormSectionSliceDefault,
      DiscountSectionSlice,
      DiscountSectionSliceDefaultItem,
      DiscountSectionSliceVariation,
      DiscountSectionSliceDefault,
      FeaturedProductsSlice,
      FeaturedProductsSliceVariation,
      FeaturedProductsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageLeftSlice,
      ImageLeftSliceDefaultPrimary,
      ImageLeftSliceVariation,
      ImageLeftSliceDefault,
      ImageRightSlice,
      ImageRightSliceDefaultPrimary,
      ImageRightSliceVariation,
      ImageRightSliceDefault,
      MyValuesSlice,
      MyValuesSliceDefaultItem,
      MyValuesSliceVariation,
      MyValuesSliceDefault,
      ProductListSlice,
      ProductListSliceVariation,
      ProductListSliceDefault,
      ShopByCategorySliceSlice,
      ShopByCategorySliceSliceDefaultPrimary,
      ShopByCategorySliceSliceDefaultItem,
      ShopByCategorySliceSliceVariation,
      ShopByCategorySliceSliceDefault,
      TalkAboutSlice,
      TalkAboutSliceDefaultItem,
      TalkAboutSliceVariation,
      TalkAboutSliceDefault,
    };
  }
}
