// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Featured Products documents
 */
interface FeaturedProductsDocumentData {
  /**
   * Product Main Image field in *Featured Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.featured_product_main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_product_main_image: prismic.ImageField<never>;

  /**
   * Product Name field in *Featured Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.product_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_name: prismic.KeyTextField;

  /**
   * Product Price field in *Featured Products*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.product_price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  product_price: prismic.NumberField;

  /**
   * Product Description field in *Featured Products*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.product_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  product_description: prismic.RichTextField;

  /**
   * Product Image 1 field in *Featured Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.product_image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image_1: prismic.ImageField<never>;

  /**
   * Product Image 2 field in *Featured Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.product_image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image_2: prismic.ImageField<never>;
}

/**
 * Featured Products document from Prismic
 *
 * - **API ID**: `featured_products`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeaturedProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FeaturedProductsDocumentData>,
    "featured_products",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | BestSellerSectionSlice
  | DiscountSectionSlice
  | ShopByCategorySliceSlice
  | BiographySlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | DiscountSectionSlice
  | ImageRightSlice
  | ImageLeftSlice
  | BiographySlice
  | ShopByCategorySliceSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

interface ProductsDocumentData {}

/**
 * Products document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductsDocumentData>,
    "products",
    Lang
  >;

/**
 * Item in *Settings → Header Label*
 */
export interface SettingsDocumentDataHeaderLabelItem {}

/**
 * Item in *Settings → Nav Settings*
 */
export interface SettingsDocumentDataNavSettingsItem {
  /**
   * Nav Label field in *Settings → Nav Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_settings[].nav_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nav_label: prismic.KeyTextField;

  /**
   * Nav Link field in *Settings → Nav Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_settings[].nav_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav_link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Header Label field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_label[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header_label: prismic.GroupField<
    Simplify<SettingsDocumentDataHeaderLabelItem>
  >;

  /**
   * Nav Settings field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_settings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_settings: prismic.GroupField<
    Simplify<SettingsDocumentDataNavSettingsItem>
  >;

  /**
   * CTA Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FeaturedProductsDocument
  | HomepageDocument
  | PageDocument
  | ProductsDocument
  | SettingsDocument;

/**
 * Default variation for BestSellerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BestSellerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BestSellerSection*
 */
type BestSellerSectionSliceVariation = BestSellerSectionSliceDefault;

/**
 * BestSellerSection Shared Slice
 *
 * - **API ID**: `best_seller_section`
 * - **Description**: BestSellerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BestSellerSectionSlice = prismic.SharedSlice<
  "best_seller_section",
  BestSellerSectionSliceVariation
>;

/**
 * Primary content in *Biography → Primary*
 */
export interface BiographySliceDefaultPrimary {
  /**
   * Owner Image field in *Biography → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: biography.primary.owner_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  owner_image: prismic.ImageField<never>;

  /**
   * Heading field in *Biography → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: biography.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Biography → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: biography.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Biography Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BiographySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BiographySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Biography*
 */
type BiographySliceVariation = BiographySliceDefault;

/**
 * Biography Shared Slice
 *
 * - **API ID**: `biography`
 * - **Description**: Biography
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BiographySlice = prismic.SharedSlice<
  "biography",
  BiographySliceVariation
>;

/**
 * Default variation for DiscountSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscountSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *DiscountSection*
 */
type DiscountSectionSliceVariation = DiscountSectionSliceDefault;

/**
 * DiscountSection Shared Slice
 *
 * - **API ID**: `discount_section`
 * - **Description**: DiscountSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DiscountSectionSlice = prismic.SharedSlice<
  "discount_section",
  DiscountSectionSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_heading: prismic.KeyTextField;

  /**
   * Hero Tagline field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_tagline: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageLeft → Primary*
 */
export interface ImageLeftSliceDefaultPrimary {
  /**
   * Section Image field in *ImageLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_left.primary.section_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_image: prismic.ImageField<never>;

  /**
   * Section Content field in *ImageLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_left.primary.section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;
}

/**
 * Default variation for ImageLeft Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageLeftSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageLeftSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageLeft*
 */
type ImageLeftSliceVariation = ImageLeftSliceDefault;

/**
 * ImageLeft Shared Slice
 *
 * - **API ID**: `image_left`
 * - **Description**: ImageLeft
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageLeftSlice = prismic.SharedSlice<
  "image_left",
  ImageLeftSliceVariation
>;

/**
 * Primary content in *ImageRight → Primary*
 */
export interface ImageRightSliceDefaultPrimary {
  /**
   * Section Image field in *ImageRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.section_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_image: prismic.ImageField<never>;

  /**
   * Section Content field in *ImageRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_right.primary.section_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_content: prismic.RichTextField;
}

/**
 * Default variation for ImageRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageRightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageRightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageRight*
 */
type ImageRightSliceVariation = ImageRightSliceDefault;

/**
 * ImageRight Shared Slice
 *
 * - **API ID**: `image_right`
 * - **Description**: ImageRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageRightSlice = prismic.SharedSlice<
  "image_right",
  ImageRightSliceVariation
>;

/**
 * Primary content in *ShopByCategorySlice → Primary*
 */
export interface ShopByCategorySliceSliceDefaultPrimary {
  /**
   * Heading field in *ShopByCategorySlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_by_category_slice.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ShopByCategorySlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_by_category_slice.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *ShopByCategorySlice → Items*
 */
export interface ShopByCategorySliceSliceDefaultItem {
  /**
   * Category Name field in *ShopByCategorySlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_by_category_slice.items[].category_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_name: prismic.KeyTextField;

  /**
   * Category Image field in *ShopByCategorySlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_by_category_slice.items[].category_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  category_image: prismic.ImageField<never>;
}

/**
 * Default variation for ShopByCategorySlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopByCategorySliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShopByCategorySliceSliceDefaultPrimary>,
  Simplify<ShopByCategorySliceSliceDefaultItem>
>;

/**
 * Slice variation for *ShopByCategorySlice*
 */
type ShopByCategorySliceSliceVariation = ShopByCategorySliceSliceDefault;

/**
 * ShopByCategorySlice Shared Slice
 *
 * - **API ID**: `shop_by_category_slice`
 * - **Description**: ShopByCategorySlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopByCategorySliceSlice = prismic.SharedSlice<
  "shop_by_category_slice",
  ShopByCategorySliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FeaturedProductsDocument,
      FeaturedProductsDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductsDocument,
      ProductsDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataHeaderLabelItem,
      SettingsDocumentDataNavSettingsItem,
      AllDocumentTypes,
      BestSellerSectionSlice,
      BestSellerSectionSliceVariation,
      BestSellerSectionSliceDefault,
      BiographySlice,
      BiographySliceDefaultPrimary,
      BiographySliceVariation,
      BiographySliceDefault,
      DiscountSectionSlice,
      DiscountSectionSliceVariation,
      DiscountSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageLeftSlice,
      ImageLeftSliceDefaultPrimary,
      ImageLeftSliceVariation,
      ImageLeftSliceDefault,
      ImageRightSlice,
      ImageRightSliceDefaultPrimary,
      ImageRightSliceVariation,
      ImageRightSliceDefault,
      ShopByCategorySliceSlice,
      ShopByCategorySliceSliceDefaultPrimary,
      ShopByCategorySliceSliceDefaultItem,
      ShopByCategorySliceSliceVariation,
      ShopByCategorySliceSliceDefault,
    };
  }
}
