// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  best_seller_section: dynamic(() => import("./BestSellerSection")),
  biography: dynamic(() => import("./Biography")),
  discount_section: dynamic(() => import("./DiscountSection")),
  hero: dynamic(() => import("./Hero")),
  image_left: dynamic(() => import("./ImageLeft")),
  image_right: dynamic(() => import("./ImageRight")),
  shop_by_category_slice: dynamic(() => import("./ShopByCategorySlice")),
};
