// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  best_seller_section: dynamic(() => import("./BestSellerSection")),
  biography: dynamic(() => import("./Biography")),
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  discount_section: dynamic(() => import("./DiscountSection")),
  featured_products: dynamic(() => import("./FeaturedProducts")),
  hero: dynamic(() => import("./Hero")),
  image_left: dynamic(() => import("./ImageLeft")),
  image_right: dynamic(() => import("./ImageRight")),
  my_values: dynamic(() => import("./MyValues")),
  product_list: dynamic(() => import("./ProductList")),
  shop_by_category_slice: dynamic(() => import("./ShopByCategorySlice")),
  talk_about: dynamic(() => import("./TalkAbout")),
};
